when:
  - event: push
    branch: main
  - event: tag
    ref: refs/tags/v*

steps:
  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: smartinfrasolutions/cifs_exporter
      username: smartinfrasolutions
      password:
        from_secret: docker_token
      platforms: linux/amd64
      dockerfile: Dockerfile
      context: .
      auto_tag: true
